<a href="https://colab.research.google.com/github/BhuvanHande/ML-Lab/blob/main/ML%20lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np
import pandas as pd
a=np.array([10,20,30,40])
print(a)

b=np.arange(1,11)
print(b)

for i in range (10,0,-1):
  print(i)

[10 20 30 40]
[ 1  2  3  4  5  6  7  8  9 10]
10
9
8
7
6
5
4
3
2
1


In [18]:
# import numpy as np
a = np.array([[1,2],
            [3,4]])
b = np.array([[2,4],
            [6,8]])
print(a*b)
print(a-b)

[[ 2  8]
 [18 32]]
[[-1 -2]
 [-3 -4]]


In [19]:
marks=np.array([70,65,50,75])
print(np.mean(marks))
print(np.max(marks))

65.0
75


In [23]:
df=pd.read_excel('/content/export.xlsx')
df.head(5)
df.head(time>)

,time,temp,dwpt,rhum,prcp,snow,wdir,wspd,wpgt,pres,tsun,coco
0,2026-07-21 00:30:00,21.1,18.8,87,0.0,NaN,262,16.9,NaN,1012.7,NaN,3
1,2026-07-21 01:30:00,20.7,18.8,89,0.0,NaN,261,15.8,NaN,1012.1,NaN,3
2,2026-07-21 02:30:00,20.4,18.7,90,0.0,NaN,260,15.5,NaN,1011.6,NaN,3
3,2026-07-21 03:30:00,20.1,18.8,92,0.0,NaN,262,16.2,NaN,1011.3,NaN,3
4,2026-07-21 04:30:00,20.0,18.7,92,0.0,NaN,262,16.2,NaN,1011.3,NaN,3


### Cleaning the Data: Filtering for the last 7 days and afternoon hours